 DELETE FROM PRESENTATIONTYPES;
 DELETE FROM GROUPTYPES;
 DELETE FROM ATTRIBUTETYPES;
 DELETE FROM LICENSE;
 DELETE FROM ATTRIBUTEGROUP;
 DELETE FROM ATTRIBUTE;
 DELETE FROM VALUE;
 DELETE FROM LICENSECONTENT;
 DELETE FROM PRESENTATION
 
 
 