CREATE TABLE PRESENTATIONTYPES (      
       ID BIGINT PRIMARY KEY,
       KEY VARCHAR(256) NOT NULL,
       VALUE_DK VARCHAR(256) NOT NULL,                                   
       VALUE_EN VARCHAR(256) NOT NULL
);
CREATE UNIQUE INDEX PRESTYPE_ID_IN ON PRESENTATIONTYPES(ID);

CREATE TABLE GROUPTYPES (      
       ID BIGINT PRIMARY KEY,
       KEY VARCHAR(256) NOT NULL,
       VALUE_DK VARCHAR(256) NOT NULL,
       VALUE_EN VARCHAR(256) NOT NULL,                                 
       MUSTGROUP BOOLEAN NOT NULL,
       QUERYSTRING VARCHAR(2048) NOT NULL,
       DESCRIPTION_DK VARCHAR(512) NOT NULL,
       DESCRIPTION_EN VARCHAR(512) NOT NULL
);
CREATE UNIQUE INDEX GROUPTYPE_ID_IN ON GROUPTYPES(ID);

CREATE TABLE ATTRIBUTETYPES (      
       ID BIGINT PRIMARY KEY,
       VALUE VARCHAR(256) NOT NULL                                    
);
CREATE UNIQUE INDEX ATTTYPE_ID_IN ON ATTRIBUTETYPES(ID);

CREATE TABLE LICENSE (
       ID BIGINT PRIMARY KEY,
       NAME VARCHAR(256) NOT NULL,
       NAME_EN VARCHAR(256) NOT NULL,
       DESCRIPTION_DK VARCHAR(1024) NOT NULL,
       DESCRIPTION_EN VARCHAR(1024) NOT NULL,
       VALIDFROM VARCHAR(32) NOT NULL,
       VALIDTO VARCHAR(32) NOT NULL
);       
CREATE UNIQUE INDEX LICENSE_ID_IN ON LICENSE(ID);

CREATE TABLE ATTRIBUTEGROUP (
       ID BIGINT PRIMARY KEY,
       NUMBER INT NOT NULL,
       LICENSEID BIGINT NOT NULL

);       
CREATE UNIQUE INDEX ATTRGRP_ID_IN ON ATTRIBUTEGROUP(ID);
CREATE INDEX ATTRGRP_LICENSEID_IN ON ATTRIBUTEGROUP(LICENSEID);

CREATE TABLE ATTRIBUTE (
       ID BIGINT PRIMARY KEY,
       NAME VARCHAR(256) NOT NULL,
       ATTRIBUTEGROUPID BIGINT NOT NULL

);       
CREATE UNIQUE INDEX ATTRIBUTE_ID_IN ON ATTRIBUTE(ID);
CREATE INDEX ATTR_GROUPID_IN ON ATTRIBUTE(ATTRIBUTEGROUPID);

CREATE TABLE VALUE (
       ID BIGINT PRIMARY KEY,
       VALUE VARCHAR(256) NOT NULL,
       ATTRIBUTEID BIGINT NOT NULL

);       
CREATE UNIQUE INDEX VALUE_ID_IN ON VALUE(ID);
CREATE INDEX VALUE_ATTRID_IN ON VALUE(ATTRIBUTEID);

CREATE TABLE LICENSECONTENT (
       ID BIGINT PRIMARY KEY,       
       NAME VARCHAR(256) NOT NULL,       
       LICENSEID BIGINT NOT NULL

);       
CREATE UNIQUE INDEX LICCONTENT_ID_IN ON LICENSECONTENT(ID);
CREATE INDEX LICCONTENT_LICID_IN ON LICENSECONTENT(LICENSEID);

CREATE TABLE PRESENTATION (
       ID BIGINT PRIMARY KEY,
       NAME VARCHAR(256) NOT NULL,
       LICENSECONTENTID BIGINT NOT NULL

);       
CREATE UNIQUE INDEX PRESENTATION_ID_IN ON PRESENTATION(ID);
CREATE INDEX PRES_LICCONTID_IN ON PRESENTATION(LICENSECONTENTID);

